### ISSUE TITLE
Error: Cannot find module './_baseTrim'

### ISSUE THREAD

**Issue by Ay-Seton** [DavidOmole/Celestial-app#1]
When I run npm start in the application folder I get the error below:

> set PORT=3006 && react-scripts start

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module './_baseTrim'

**Comment by DavidOmole** [comment]
Hi! Try deleting the entire node-modules folder with `rm -rf node_modules` and reinstalling  with `npm install`
